//
//  DMPhotoThumbsStyleKit.h
//  DMPhotoThumbs
//
//  Created by Dmitry Avvakumov on 02.11.15.
//  Copyright (c) 2015 none. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface DMPhotoThumbsStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkOnIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkOffIconTargets;

// Colors
+ (UIColor*)mainColor;

// Generated Images
+ (UIImage*)imageOfCheckOnIcon;
+ (UIImage*)imageOfCheckOffIcon;

@end
